steps:
- id: 'builder' 
  name: 'gcr.io/yzhang-test-personal-project/mirror-mydesktop'

# ################################
# Verify Version
# ################################
- id: 'version'
  name: 'gcr.io/yzhang-test-personal-project/mirror-mydesktop'
  entrypoint: 'bash'
  args: 
  - '-c'
  - |
    echo '\n\n'
    echo '#######################'
    echo '# check folder'
    echo '#######################'
    pwd
    ls -al
    cd /workspace/.ssh
    ls -al


    echo '#######################'
    echo '# check Linux version'
    echo '#######################'
    uname -a
    ls /etc/*release
    cat /etc/lsb-release

    echo '#######################'
    echo '# check Terraform version'
    echo '#######################'    
    terraform version

    echo '#######################'
    echo '# check Python version'
    echo '#######################'    
    python3 -V
    python3 -m pip --version

    echo '#######################'
    echo '# check Google SDK version'
    echo '#######################'
    gcloud version

    echo '#######################'
    echo '# check repo'
    echo '#######################'

    echo '#######################'
    echo '# check python script'
    echo '#######################'
    
